[deps]
DiffEqParamEstim = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GRAPE = "6b52fcaf-80fe-489a-93e9-9f92080510be"
Krotov = "b05dcdc7-62f6-4360-bf2c-0898bba419de"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumControl = "8a270532-f23f-47a8-83a9-b33d10cad486"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"
