[deps]
DiffEqParamEstim = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GRAPE = "6b52fcaf-80fe-489a-93e9-9f92080510be"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Krotov = "b05dcdc7-62f6-4360-bf2c-0898bba419de"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OptimizationPolyalgorithms = "500b13db-7e66-49ce-bda4-eed966be6282"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumControl = "8a270532-f23f-47a8-83a9-b33d10cad486"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
